### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Habetdin**
- Fix topic names (use slashes instead of backslashes)
- Update the cite entry (page numbers are known now)

cc: @TixiaoShan

### CODE REVIEW

**Comment by TixiaoShan** [comment]
@Habetdin 
Thanks for the commit. Feel free to take a look at a new data-set.
https://github.com/TixiaoShan/Stevens-VLP16-Dataset

**Comment by Habetdin** [comment]
@TixiaoShan np :smile: Thanks, noticed the fresh dataset too.
Btw, how to generate valid `/tf` for LeGO-LOAM? Seems like my own data is missing proper _baselink-to-map_ transformation:
> For frame [base_link]: No transform to fixed frame [map]. TF error: [Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.]

**Comment by TixiaoShan** [comment]
@Habetdin 
Actually, you don't need to give any tf to LeGO-LOAM. The transformations between /camera_init (world) and /camera (local) is given in transformFusion.cpp. The static transformation between /camera_init and /map, /camera and /base_link is specified in run.launch. You only need to provide /velodyne_points with /imu/data as optional.

**Comment by Habetdin** [comment]
@TixiaoShan
Oh, okay, thanks for the information. Found out that my problem wasn't in wrong `/tf` but in wrong velodyne topic: I had raw `/velodyne_packets`, so converting it to `/velodyne_points` with `rosrun velodyne_pointcloud cloud_node _calibration:=/path/to/VLP16db.yaml` solved the issue.

**Pull request merged**
